### ISSUE TITLE
$this->displayName is not valid but required

### ISSUE THREAD

**Issue by samy** [PrestaShop/PrestaShop-norm-validator#2]
If you submit a module to the validator, it fails on the $this->displayName line at the beginning of each module : it is not valid (CamelCase syntax), but it is required.

For example, if you replace it by $this->display_name, the module throws a fatal error.

**Comment by jeromenadaud** [comment]
Hi,

thank you for reporting.
This issue is fixed on PrestaShop Validator.

Best regards.
